# Generated by Django 5.1.7 on 2025-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoora', '0002_remove_topic_interested_users'),
        ('users', '0002_remove_user_is_admin_user_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topics_of_interest',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='cuoora.topic'),
        ),
    ]
