# Generated by Django 5.1.7 on 2025-04-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuoora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='interested_users',
        ),
    ]
