# Generated by Django 5.1.7 on 2025-04-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuoora', '0002_remove_topic_interested_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='cuoora.topic'),
        ),
    ]
